modules/tickets/__init__.py
from flask import Blueprint

ticketsBP = Blueprint('ticket_blueprint', __name__)

@ticketsBP.before_request
def validate_user_session():
     if "username" not in session:
          return redirect(url_for("user_blueprint.login"))


from .routes import *

modules/tickets/controller.py
from flask import *
import datetime

from extensions import db
from modules.tickets.model import Ticket
from modules.usuarios.model import *
from modules.historical.controller import *


def getAllTicketsController():
     tickets = db.paginate((db.select(Ticket).order_by(Ticket.id.desc()).limit(200)), per_page=10)
     return tickets

def createTicketController(data):
     try:
          creator = db.session.query(Usuario).filter_by(username = session["username"]).first()
          assigned= db.session.query(Usuario).filter_by(username = data["assigned_to"].lower()).first()
          
          ticket = Ticket(
               data["title"], 
               data["description"],
               creator.id,
               assigned.id,
               data["state"].lower(),
               str((datetime.datetime.now()))
          )
          db.session.add(ticket)
          db.session.commit()
          createRegister("Create",f"Creación de ticket {ticket.id}")

          flash("Ticket cargado correctamente")
          return redirect(url_for("ticket_blueprint.index"))
     except Exception as e:
          flash(f"Error al cargar ticket. {e}")
          return redirect(url_for("ticket_blueprint.newTicket"))

def editTicketController(requestedData, ticketId):
     try:
          # Obtener el ticket a editar
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()

          # Actualizar los campos del ticket con los datos enviados en el formulario
          ticket.title = requestedData['title']
          ticket.description = requestedData['description']
          ticket.assigned_to = requestedData['assigned_to']
          ticket.lastmodif = datetime.datetime.today()
          ticket.state = requestedData['state']
          if (ticket.state.lower() == "cerrado"):
               ticket.sysactive = '0'

          # Guardar los cambios en la base de datos
          db.session.commit()
          createRegister("Edit", f"Ticket {ticket.id}. User: {session['username']}")

          flash(f"Ticket actualizado correctamente. Id: {ticket.id} ")
          return 
     except Exception as e:
          flash(f"Error en actualización de ticket. \n {e}")
          return 

modules/tickets/routes.py
from flask import request, render_template, redirect, url_for, session
import datetime
from sqlalchemy import func, DateTime, Time


from modules.tickets import ticketsBP
from modules.tickets.controller import *


@ticketsBP.route("/index", methods=["GET"])
def index():
     users = db.session.query(Usuario).order_by(Usuario.id.desc()).all()   
     data = getAllTicketsController()

     return render_template(
          "ticket/index.html", 
          data = data,
          admin=session["admin"],
          users = users,
          username = session["username"],
          pagination = data,
          endpoint = "ticket_blueprint.index"
     )

@ticketsBP.route("/newTicket",methods=["GET","POST"])
def newTicket():
     users = db.session.query(Usuario).all()
     if request.method == "GET":
          return render_template("ticket/newTicketForm.html", admin=session["admin"], users = users, username=session["username"])
     else:
          data = request.form.to_dict()
          createTicketController(data)
          return render_template("ticket/newTicketForm.html", admin=session["admin"], users = users,  username=session["username"])

@ticketsBP.route("/edit/<int:ticketId>", methods=["GET","POST"])
def editTicket(ticketId):
     if request.method == "GET":
          users = db.session.query(Usuario).all()
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()
          return render_template("ticket/edit_ticket.html", ticket=ticket, users =users, username=session["username"])
     else:
          data = request.form.to_dict()
          editTicketController(data, ticketId)
          return redirect(url_for("ticket_blueprint.index"))

@ticketsBP.route("/delete/<int:ticketId>", methods=["GET","POST"])
def deleteTicket(ticketId):
     try:
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()
          # 'Delete' the ticket from the database
          # Here we set the ticket in the current status and 
          db.session.commit()
          flash(f"Ticket eliminado correctamente. Id: {ticket.id} ")
          return redirect(url_for("ticket_blueprint.index"))
     except Exception as e:
          flash(f"Error en actualización de ticket. \n {e}")
          return
     


# ---- Assigned to user
# ---- This should show the tickets that are:
#         * Tickets "Closed" on the day of the current date
#         * All "Open" tickets
#         * All tickets "in progress"
@ticketsBP.route("/assigned", methods = ["GET","POST"])
def assignedToMe():
     user = db.session.query(Usuario).filter_by(username=session["username"]).first()
     
     today_date = datetime.datetime.today().date()

     end_of_day = datetime.time(23, 59, 59)
     end_of_day_datetime = datetime.datetime.combine(datetime.datetime.today(), end_of_day)

     filter_condition1 = ((Ticket.state == "cerrado") &
                    (func.date(Ticket.lastmodif) == today_date) &
                    (Ticket.lastmodif.cast(DateTime) <= end_of_day_datetime))
     filter_condition2 = ((Ticket.sysactive == '0') &
                    (func.date(Ticket.lastmodif) == today_date) &
                    (Ticket.lastmodif.cast(DateTime) <= end_of_day_datetime))

     print(str(func.Ticket.lastmodif))

     tickets = db.session.query(Ticket).filter(

          (Ticket.assigned_to == user.id) & 
          (
               (Ticket.state == "abierto") | 
               filter_condition1|
               (Ticket.sysactive == '1') |
               ((Ticket.sysactive == '0') & (((str(Ticket.lastmodif)).split(' '))[0] == datetime.datetime.today().date()))
          )
     ).all()

     users = db.session.query(Usuario).all()
     return render_template("ticket/assigned.html", tickets=tickets, data = tickets, users =users, admin=session["admin"], username=session["username"])

tickets/controller.py
from flask import *
import datetime

from extensions import db
from tickets.model import Ticket
from usuarios.model import *

def getAllTicketsController():
     tickets = db.paginate((db.select(Ticket).order_by(Ticket.id.asc())), per_page=20)
     return tickets

def createTicketController(data):
     try:
          creator = db.session.query(Usuario).filter_by(username = session["username"]).first()
          assigned= db.session.query(Usuario).filter_by(username = data["assigned_to"].lower()).first()
          
          ticket = Ticket(
               data["title"], 
               data["description"],
               creator.id,
               assigned.id,
               data["state"].lower(),
               str((datetime.datetime.now()))
          )
          db.session.add(ticket)
          db.session.commit()

          flash("Ticket cargado correctamente")
          return redirect(url_for("ticket_blueprint.index"))
     except Exception as e:
          flash(f"Error al cargar ticket. {e}")
          return redirect(url_for("ticket_blueprint.newTicket"))

def editTicketController(requestedData, ticketId):
     try:
          # Obtener el ticket a editar
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()

          # Actualizar los campos del ticket con los datos enviados en el formulario
          ticket.title = requestedData['title']
          ticket.description = requestedData['description']
          ticket.assigned_to = requestedData['assigned_to']
          ticket.lastmodif = datetime.datetime.today()
          ticket.state = requestedData['state']
          if (ticket.state.lower() == "cerrado"):
               ticket.sysactive = '0'

          # Guardar los cambios en la base de datos
          db.session.commit()
          flash(f"Ticket actualizado correctamente. Id: {ticket.id} ")
          return 
     except Exception as e:
          flash(f"Error en actualización de ticket. \n {e}")
          return 

tickets/routes.py
from flask import request, render_template, redirect, url_for, session
import datetime
from sqlalchemy import func, DateTime, Time


from tickets import ticketsBP
from tickets.controller import *



@ticketsBP.route("/index", methods=["GET"])
def index():
     users = db.session.query(Usuario).order_by(Usuario.id.desc()).all()   
     data = getAllTicketsController()

     return render_template(
          "ticket/index.html", 
          data = data,
          admin=session["admin"],
          users = users,
          username = session["username"],
          pagination = data,
          endpoint = "ticket_blueprint.index"
     )

@ticketsBP.route("/newTicket",methods=["GET","POST"])
def newTicket():
     users = db.session.query(Usuario).all()
     if request.method == "GET":
          return render_template("ticket/newTicketForm.html", admin=session["admin"], users = users, username=session["username"])
     else:
          data = request.form.to_dict()
          createTicketController(data)
          return render_template("ticket/newTicketForm.html", admin=session["admin"], users = users,  username=session["username"])

@ticketsBP.route("/edit/<int:ticketId>", methods=["GET","POST"])
def editTicket(ticketId):
     if request.method == "GET":
          users = db.session.query(Usuario).all()
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()
          return render_template("ticket/edit_ticket.html", ticket=ticket, users =users, username=session["username"])
     else:
          data = request.form.to_dict()
          editTicketController(data, ticketId)
          return redirect(url_for("ticket_blueprint.index"))

@ticketsBP.route("/delete/<int:ticketId>", methods=["GET","POST"])
def deleteTicket(ticketId):
     try:
          ticket = db.session.query(Ticket).filter_by(id=ticketId).first()
          # 'Delete' the ticket from the database
          
          db.session.commit()
          flash(f"Ticket eliminado correctamente. Id: {ticket.id} ")
          return redirect(url_for("ticket_blueprint.index"))
     except Exception as e:
          flash(f"Error en actualización de ticket. \n {e}")
          return
     
@ticketsBP.route("/assigned", methods = ["GET","POST"])
def assignedToMe():
     user = db.session.query(Usuario).filter_by(username=session["username"]).first()
     
     today_date = datetime.datetime.today().date()

     end_of_day = datetime.time(23, 59, 59)
     end_of_day_datetime = datetime.datetime.combine(datetime.datetime.today(), end_of_day)

     filter_condition1 = ((Ticket.state == "cerrado") &
                    (func.date(Ticket.lastmodif) == today_date) &
                    (Ticket.lastmodif.cast(DateTime) <= end_of_day_datetime))
     filter_condition2 = ((Ticket.sysactive == '0') &
                    (func.date(Ticket.lastmodif) == today_date) &
                    (Ticket.lastmodif.cast(DateTime) <= end_of_day_datetime))

     print(str(func.Ticket.lastmodif))

     tickets = db.session.query(Ticket).filter(

          (Ticket.assigned_to == user.id) & 
          (
               (Ticket.state == "abierto") | 
               filter_condition1|
               (Ticket.sysactive == '1') |
               ((Ticket.sysactive == '0') & (((str(Ticket.lastmodif)).split(' '))[0] == datetime.datetime.today().date()))
          )
     ).all()

     users = db.session.query(Usuario).all()
     return render_template("ticket/assigned.html", tickets=tickets, data = tickets, users =users, admin=session["admin"], username=session["username"])

templates/ticket/assigned.html
{% extends "base.html" %}
{% block title %} Tickets Asignados {% endblock %}
{% block content %}
     <body>
          {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="alert alert-dismissible fade show {% if 'Error' in messages %} alert-danger {% else %} alert-success {% endif %}" role="alert">
                        <ul class="mb-0">
                            {% for message in messages %}
                                <li class="" style="list-style:none">{{ message }}</li>
                            {% endfor %}
                        </ul>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
               {% endif %}
          {% endwith %}
          <div class="container">
               <h1>Tickets asignados a ti</h1>
               <table class="table">
                    <thead>
                    <tr class="table-dark">
                         <th>ID</th>
                         <th>Título</th>
                         <th>Descripción</th>
                         <th>Creador</th>
                         <th>Asignado a</th>
                         <th>Estado</th>
                         <th>Fecha</th>
                         <th>Acciones</th>
                    </tr>
                    <tr>
                         <th></th>
                         <th></th>
                         <th></th>
                         <th></th>
                         <th></th>
                         <th></th>
                         <th></th>
                         <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ticket in tickets %}
                    <tr {% if ticket.state.lower() == "cerrado" %} class="alert alert-danger" {% else %} class="alert alert-success" {% endif %}>
                         <td>{{ ticket.id }}</td>
                         <td>{{ ticket.title }}</td>
                         <td>{{ ticket.description }}</td>
                         
                         {% for user in users %}
                              {% if user.id == ticket.creator_id %}
                                   <td>{{user.username}}</td>
                              {% endif %}
                         {% endfor %}
                         {% for user in users %}
                              {% if user.id == ticket.assigned_to %}
                                   <td>{{user.username}}</td>
                              {% endif %}
                         {% endfor %}
                         <td>{{ ticket.state }}</td>
                         <td>{{ ticket.date }}</td>
                         <td class="">
                              <a href="{{ url_for('ticket_blueprint.editTicket', ticketId=ticket.id) }}" class="btn btn-success">
                                   <i class="bi bi-pencil"></i>
                              </a>
                         </td>
                    </tr>
                    {% endfor %}
                    </tbody>
               </table>
          </div>
     </body>
{% endblock %}

templates/ticket/edit_ticket.html
{% extends "base.html" %}

{% block content %}
<h1>Editar Ticket #{{ ticket.id }}</h1>
<h3>Estado actual: {{ ticket.state }}</h3>
<form method="post" class="w-50 m-auto" action="/tickets/edit/{{ticket.id}}" id="edit-ticket-form">
     <div class="form-floating mb-3">
          <input type="text" id="titulo" name="title" class="form-control" value={{ticket.title}}>
          <label for="titulo">Título</label>
     </div>
     <div class="form-floating mb-3">
          <textarea id="descripcion" name="description" class="form-control" rows="4"
               cols="50">{{ticket.description}}</textarea>
          <label for="descripcion">Descripción</label>
     </div>
     <div class="form-floating mb-3">
          <select class="form-select" id="asignado_a" name="assigned_to" required>
               <option value="" disabled>Selecciona una opción</option>
               {% for user in users %}
                    {% if user.id == ticket.assigned_to %}
                         <option value="{{ user.id }}" selected>{{user.username.capitalize()}}</option>
                    {% else  %}
                         <option value="{{ user.id }}">{{user.username.capitalize()}}</option>
                    {% endif %}
               {% endfor %}
          </select>
          <label for="asignado_a">Asignado a</label>
     </div>
     <div class="form-floating mb-3">
          <select id="estado" name="state" class="form-select">
               <option value="Abierto">Abierto</option>
               <option value="En progreso">En progreso</option>
               <option value="Cerrado">Cerrado</option>
          </select>
          <label for="estado">Estado</label>
     </div>
     <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#edit-ticket-modal">Save Changes</button>
</form>

<!-- Modal -->
<div class="modal fade" id="edit-ticket-modal" tabindex="-1" aria-labelledby="edit-ticket-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit-ticket-modal-label">Confirmar edición de ticket</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Está seguro de que desea guardar los cambios del ticket editado?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary" form="edit-ticket-form">Guardar cambios</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/ticket/index.html
{% extends "base.html" %}
{% block title %} Inicio Tickets {% endblock %}
{% block content %}
<style>
     .deleted {
          opacity: 0.4;
          cursor: not-allowed;
     }
     .search-input {
          width: 80%;
          border: 1px black solid;
          padding: 12px 20px;
          margin: 8px 0;
          box-sizing: border-box;
          border: none;
          border-radius: 10px;
     }
     
     button {
          background-color: var(--btn-bg);
          color: white;
          padding: 12px 20px;
          border: none;
          cursor: pointer;
          border-radius: 15px;
          border: solid 2px black;
     }
</style>

<body>
     {% with messages = get_flashed_messages() %}
     {% if messages %}
     <div class="alert alert-dismissible fade show {% if 'Error' in messages %} alert-danger {% else %} alert-success {% endif %}"
          role="alert">
          <ul class="mb-0">
               {% for message in messages %}
               <li class="" style="list-style:none">{{ message }}</li>
               {% endfor %}
          </ul>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
     {% endif %}
     {% endwith %}
     <div class="container">
          <h1 class="d-flex justify-content-center mb-3">Todos los Tickets</h1>
          <div class="table-responsive">
               <input class="search-input" style="border:2px solid black;" type="text" id="search-box" placeholder="Buscar usuarios..."
               onkeyup="searchUsers()">
               <button style="border:2px solid black;" class="W-20" type="submit" onclick="searchUsers()">
                    <i class="bi bi-search"></i>
               </button>
               <button style="border:2px solid black;" class="W-20" type="button" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">
                    <i class="bi bi-plus-circle-dotted p-1"></i>
                    Nuevo Ticket
               </button>
               <!-- Modal -->
               <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
               aria-hidden="true">
               <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                         <div class="modal-header">
                              <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Usuario</h1>
                              <button type="button btn" class="btn-close button" data-bs-dismiss="modal"
                                   aria-label="Close"></button>
                         </div>
                         <div class="modal-body">
                              <div class="card">
                                   <div class="modal-header card-header">
                                        <h4 class="card-title text-center m-auto">Crear Usuario</h4>
                                   </div>
                                   <div class="card-body">
                                        <form class="m-auto" action="/user/create" method="POST">
                                             <div class="form-floating mb-3">
                                                  <input type="text" name="username" class="form-control" id="inputNombre"
                                                       placeholder="Introduce tu nombre" required>
                                                  <label for="inputNombre" class="form-label">Nombre</label>
                                             </div>
                                             <div class="form-floating mb-3">
                                                  <input type="email" name="email" class="form-control" id="inputEmail"
                                                       placeholder="Introduce tu correo electrónico" required>
                                                  <label for="inputEmail" class="form-label">Correo electrónico</label>
                                             </div>
                                             <div class="form-floating mb-3">
                                                  <input type="password" name="password" class="form-control" id="inputPassword"
                                                       placeholder="Introduce tu contraseña" required>
                                                  <label for="inputPassword" class="form-label">Contraseña</label>
                                             </div>
                                             <div class="form-group mb-3">
                                                  <label for="isadmin">¿Es Administrador?</label>
                                                  <input type="checkbox" class="" name="isadmin" id="isadmin"
                                                       placeholder="¿Es Administrador?">
                                             </div>
                                             <button type="submit" class="btn button fs-5">Guardar</button>
                                        </form>
                                   </div>
                              </div>
                         </div>
                         <div class="modal-footer">
                         </div>
                    </div>
               </div>
          </div>
               <table id="tickets-table" class="table align-middle ">
                    <thead>
                         <tr class="table-dark">
                              <th>ID</th>
                              <th>Título</th>
                              <th>Descripción</th>
                              <th>Creador</th>
                              <th>Asignado a</th>
                              <th>Estado</th>
                              <th>Fecha</th>
                              <th class="{% if admin!='admin' %} d-none {% endif %}">Opciones</th>
                         </tr>
                         <tr>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th></th>
                              <th class="{% if admin!='admin' %} d-none {% endif %}"></th>
                         </tr>
                    </thead>
                    <tbody>
                         <!-- Aquí se generará dinámicamente la lista de tickets pendientes -->
                         {% for ticket in data %}
     
                         <tr class="
                                        {% if ticket.sysactive == '0' %} deleted {% endif %}
                                        {% if ticket.state.lower() == 'cerrado' %} table-danger {% else %} table-success {% endif %}
                                   ">
     
                              <th>
                                   <p>{{ticket.id}}</p>
                              </th>
                              <th>
                                   <p>{{ticket.title}}</p>
                              </th>
                              <th>
                                   <p>{{ticket.description}}</p>
                              </th>
     
                              {% for user in users %}
                              {% if user.id == ticket.creator_id %}
                              <th>
                                   <p>{{user.username}}</p>
                              </th>
                              {% endif %}
                              {% endfor %}
                              {% for user in users %}
                              {% if user.id == ticket.assigned_to %}
                              <th>
                                   <p> {{user.username}} </p>
                              </th>
                              {% endif %}
                              {% endfor %}
     
                              <th>
                                   <p>{{ticket.state}}</p>
                              </th>
                              <th>
                                   <p>{{ticket.lastmodif}}</p>
                              </th>
     
                              <th class="{% if admin!='admin' %} d-none {% endif %}">
                                   <a href="{{ url_for('ticket_blueprint.editTicket', ticketId=ticket.id) }}"
                                        class="{% if ticket.sysactive == '0' %} disabled {% endif %} btn btn-success">
                                        <i class="bi bi-pencil"></i>
                                   </a>
                                   <a type="button" data-bs-toggle="modal" data-bs-target="#delete-ticket-modal"
                                        class="btn btn-danger {% if ticket.sysactive == '0' %} disabled {% endif %}">
                                        <i class="bi bi-trash"></i>
                                   </a>
                              </th>
     
                              <!-- Modal de confirmación de eliminación -->
                                   <div class="modal fade " id="delete-ticket-modal" tabindex="-1"
                                        aria-labelledby="delete-ticket-modal-label" aria-hidden="true">
                                        <div class="modal-dialog">
                                             <div class="modal-content">
                                                  <div class="modal-header alert alert-dark">
                                                       <h5 class="modal-title" id="delete-ticket-modal-label">Confirmar elminación
                                                            de ticket</h5>
                                                       <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                  </div>
                                                  <div class="modal-body">
                                                       ¿Está seguro de que desea eliminar este ticket?
                                                  </div>
                                                  <div class="modal-footer bg-secondary">
                                                       <button type="button" class="btn btn-dark"
                                                            data-bs-dismiss="modal">Cancelar</button>
                                                       <a href="{{ url_for('ticket_blueprint.deleteTicket', ticketId=ticket.id) }}"
                                                            type="submit" class="btn btn-danger"
                                                            form="delete-ticket-form">Confirmar</a>
                                                  </div>
                                             </div>
                                        </div>
                                   </div>
     
                              </tr>
                         {% endfor %}
     
                    </tbody>
               </table>
          </div>
     </div>
     <div class="container" style="z-index: -1;">
          <nav aria-label="page navigation example">
               <ul class="pagination">
                    <li class="page-item">
                         <a class="page-link {% if not data.has_prev %} disabled {% endif %}" href="{{ url_for(endpoint, page=1) }}">&laquo;</a>
                    </li>
                    <li class="page-item">
                         <a class="page-link {% if not data.has_prev %} disabled {% endif %}" href="{{ url_for(endpoint, page=data.prev_num) }}">&lt;</a>
                    </li>
                    {% for page in data.iter_pages() %}
                         {% if page %}
                              <li class="page-item {% if page == data.page %} active {% endif %}">
                                   <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                              </li>
                         {% else %}
                              <li class="page-item disabled"><span class="page-link">&hellip;</span></li>
                         {% endif %}
                    {% endfor %}
                    <li class="page-item">
                    <a class="page-link {% if not data.has_next %} disabled {% endif %}" href="{{ url_for(endpoint, page=data.next_num) }}">&gt;</a>
                    </li>
                    <li class="page-item">
                         <a class="page-link {% if not data.has_next %} disabled {% endif %}" href="{{ url_for(endpoint, page=data.pages) }}">&raquo;</a>
                    </li>
               </ul>
          </nav>
     </div>

     <script>
          function searchUsers() {
               var input, filter, table, tr, td, i, txtValue;
               input = document.getElementById("search-box");
               filter = input.value.toUpperCase();
               table = document.getElementById("tickets-table");
               tr = table.getElementsByTagName("tr");
               for (i = 0; i < tr.length; i++) {
                    td = tr[i].getElementsByTagName("td")[0];
                    if (td) {
                         txtValue = td.textContent || td.innerText;
                         if (txtValue.toUpperCase().indexOf(filter) > -1) {
                              tr[i].style.display = "";
                         } else {
                              tr[i].style.display = "none";
                         }
                    }
               }
          }
     </script>
</body>
{% endblock %}